schemaVersion: 2.1.0
metadata:
  generateName: merge-pdf
attributes:
  controller.devfile.io/scc: container-build
  controller.devfile.io/storage-type: common
  metadata-name-field: generateName
  metadata-name-original-value: merge-pdf-
components:
  - attributes:
      che-code.eclipse.org/contribute-volume-mount/checode: /checode
      che-code.eclipse.org/contributed-container: sunix-mergepdf
      che-code.eclipse.org/original-memoryLimit: 512M
    container:
      command:
        - /checode/entrypoint-volume.sh
      cpuLimit: 500m
      cpuRequest: 30m
      env:
        - name: VSCODE_NODEJS_RUNTIME_DIR
          value: /usr/local/bin
      image: quay.io/sunix/mergepdf
      memoryLimit: 1.59G
      memoryRequest: 256Mi
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: checode
          path: /checode
    name: sunix-mergepdf
commands:
  - exec:
      commandLine: set -o xtrace; pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps && ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps && echo Done!
      component: sunix-mergepdf
      label: Merge PDF files
      workingDir: /projects/
    id: merge-pdf-files
  - exec:
      commandLine: set -o xtrace; for jpgfile in $(ls *.*g); do convert "$jpgfile"  "$jpgfile".pdf; done && echo Done!
      component: sunix-mergepdf
      label: Convert images to PDF
      workingDir: /projects/
    id: convert-images-to-pdf
